export const courses = [
	{
		id: 1,
		title: 'User Experience Design Essentials',
		category: 'Design',
		price: 500,
		rating: 5,
		reviews: 20,
		image: 'https://picsum.photos/seed/design1/400/300',
		color: 'bg-[#FFD5C2]',
	},
	{
		id: 2,
		title: 'Financial Analysis and Business Strategy',
		category: 'Business',
		price: 500,
		rating: 4,
		reviews: 102,
		image: 'https://picsum.photos/seed/biz1/400/300',
		color: 'bg-[#E0E0FF]',
	},
	{
		id: 3,
		title: 'Modern Marketing and Digital Branding',
		category: 'Business',
		price: 500,
		rating: 4,
		reviews: 102,
		image: 'https://picsum.photos/seed/biz2/400/300',
		color: 'bg-[#D1C4E9]',
	},
	{
		id: 4,
		title: 'Mastering Figma for UI Designers',
		category: 'Design',
		price: 500,
		rating: 5,
		reviews: 20,
		image: 'https://picsum.photos/seed/design2/400/300',
		color: 'bg-[#FFD5C2]',
	},
	{
		id: 5,
		title: 'Strategic Management Principles',
		category: 'Business',
		price: 500,
		rating: 4,
		reviews: 102,
		image: 'https://picsum.photos/seed/biz3/400/300',
		color: 'bg-[#E0E0FF]',
	},
	{
		id: 6,
		title: 'Corporate Finance & Risk Assessment',
		category: 'Business',
		price: 500,
		rating: 4,
		reviews: 102,
		image: 'https://picsum.photos/seed/biz4/400/300',
		color: 'bg-[#D1C4E9]',
	},
	{
		id: 7,
		title: 'Advanced Graphic Design Workshop',
		category: 'Design',
		price: 500,
		rating: 5,
		reviews: 20,
		image: 'https://picsum.photos/seed/design3/400/300',
		color: 'bg-[#FFD5C2]',
	},
	{
		id: 8,
		title: 'Entrepreneurship: Startup Launchpad',
		category: 'Business',
		price: 500,
		rating: 4,
		reviews: 102,
		image: 'https://picsum.photos/seed/biz5/400/300',
		color: 'bg-[#E0E0FF]',
	},
	{
		id: 9,
		title: 'Investment Banking Masterclass',
		category: 'Business',
		price: 500,
		rating: 4,
		reviews: 102,
		image: 'https://picsum.photos/seed/biz6/400/300',
		color: 'bg-[#D1C4E9]',
	},
]
